os: Visual Studio 2017

# Version format
version: 1.0.1.{build}

cache:
  - packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    - master
    - feature/buildRework

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
environment:
  # Version Suffix
  version_suffix: alpha

install:
  - ps: .\build\appveyor-semver.ps1
  - ps: .\build\check-release-version.ps1
  - ps: Update-AppveyorBuild -Version $Env:appveyor_version

assembly_info:
  patch: true
  file: 'src\Our.Umbraco.HCSlackNM**\AssemblyInfo.*'
  assembly_version: '$(appveyor_file_version)'
  assembly_file_version: '$(appveyor_file_version)'
  assembly_informational_version: '$(mssemver)'

build_script:
- cmd: >-
    build-appveyor.cmd

    cd..

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
  # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://www.myget.org/F/umbraco-packages/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop