version: 3.0.0.{build}

os: Visual Studio 2019

configuration: Release

branches:
  only:
    - develop
    - develop-v2
    - develop-v3
    - master
    - master-v2    
    - /v*/

environment:
  # Version Suffix
  version_suffix: alpha

install:
  - ps: .\build\appveyor-semver.ps1
  - ps: .\build\check-release-version.ps1
  - ps: Update-AppveyorBuild -Version $Env:semver

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(semver)'
  assembly_version: '$(appveyor_file_version)'
  file_version: '$(appveyor_file_version)'
  informational_version: '$(semver)'

build_script:
- cmd: >-
    cd src

    cd HealthCheckSlackNotificationMethod

    dotnet build

    cd..

artifacts:
  - path: .\src\HealthCheckSlackNotificationMethod\bin\$(CONFIGURATION)\*.nupkg
