<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ContentTargetFolders>.</ContentTargetFolders>
        <RootNamespace>Our.Umbraco.HealthCheckSlackNotificationMethod</RootNamespace>
        <!-- Symbol file configuration -->
        <DebugType>portable</DebugType>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <!-- Enable deterministic builds in CI -->
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
        <!-- SourceLink configuration -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Our.Umbraco.HealthCheckSlackNotificationMethod</PackageId>
        <Product>Our.Umbraco.HealthCheckSlackNotificationMethod</Product>
        <Title>HealthCheckSlackNotificationMethod</Title>
        <Description>This package adds a Slack Health Check Notification Method to Umbraco</Description>
        <PackageTags>umbraco plugin package slack notifications umbraco-marketplace</PackageTags>
        <Authors>Jeavon Leopold</Authors>
        <RepositoryUrl>https://github.com/CrumpledDog/Umbraco-HealthCheckSlackNotificationMethod</RepositoryUrl>
        <PackageProjectUrl>https://github.com/CrumpledDog/Umbraco-HealthCheckSlackNotificationMethod</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>slack-health-check-notification-128.png</PackageIcon>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <InformationalVersion>$(PackageVersion)</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.103" PrivateAssets="All" />
        <PackageReference Include="SlackNet" Version="0.17.8" />
        <PackageReference Include="Umbraco.Cms.Core" Version="17.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md">
          <Pack>True</Pack>
          <PackagePath>\</PackagePath>
        </None>
        <None Include="slack-health-check-notification-128.png">
          <Pack>True</Pack>
          <PackagePath></PackagePath>
        </None>
    </ItemGroup>
</Project>
